### ISSUE TITLE
Make Gramps loader messages translatable 

### ISSUE THREAD

**Issue by bartfeenstra** [bartfeenstra/betty#1237]
`GrampsLoader.load_tree()` in https://github.com/bartfeenstra/betty/blob/0.3.x/betty/gramps/loader.py#L138 logs several hardcoded messages. These should be translatable.

## Definition of Done
- Make all log messages translatable through the gettext methods o. `self._localizer`
- Remove the `@todo` comment

**Comment by RomainDereu** [comment]
@bartfeenstra 
Hi, I'd like to work on this if help is needed!

**Comment by bartfeenstra** [comment]
Hi, and welcome! This has been picked up by https://github.com/bartfeenstra/betty/pull/1238 for now. If you'd like to help out, there as some other [good first issues](https://github.com/bartfeenstra/betty/labels/good%20first%20issue) you may find interesting 😊

**Comment by bartfeenstra** [comment]
This issue is now available for anyone to pick up again 🙂
