### ISSUE TITLE
Biography section?

### ISSUE THREAD

**Issue by fatso83** [bartfeenstra/betty#1270]
Hi, I would like to add personal notes and presentations for people. Is this currently possible? I could not see anything like that on [the example page](https://ancestry.bartfeenstra.com/en/person/I0004/). I just see lists of facts, but I would like to be able to have some kind of "profile page" where one could tie the various info together.

**Comment by bartfeenstra** [comment]
Hi @fatso83, welcome to Betty! https://github.com/bartfeenstra/betty/pull/1330 was just merged, which adds note support to places, people, sources, and events, with files having had note support for some time now.

For Betty 0.4.0, later this year, I would like to focus on adding more content management features. Where notes can only contain plain text right now, I want this to contain things like Markdown, Jinja2, and HTML. They currently also do not contain any locale information, so any note is displayed in the current templates, even if it is not in the current language.

Until such improvements have been introduced, you can use these notes on your other entities, or, alternatively, [override Betty's built-in Jinja2 templates](https://betty.readthedocs.io/latest/usage/templating/) with your own, specific to your project. This approach allows you complete flexibility.

**Comment by bartfeenstra** [comment]
@fatso83 If you have specific content management requests, such as being able to parse markdown/Rest/Jinja2, or use translations, or more advanced features, please feel free to open an issue per feature so we can hash out the details there 😊
