### ISSUE TITLE
Consider adopting the GPLv3 *or later*

### ISSUE THREAD

**Issue by bartfeenstra** [bartfeenstra/betty#1526]
Betty is currently released under the *GPL License, version 3*. This is absolutely great, and compared to version 2 this allows us to combine materials release under other licenses (such as certain Creative Commons works) with Betty into a distribution/release.

However, in the future such works may be released under newer licenses that have not been explicitly made compatible in the GPL version 3 license text. We would not be able to include such works.

To prepare for those I propose we re-release Betty under the *GPL License, version 3 **or later***. This provides exactly the same protections as now, but will allow us to release Betty under a possible*GPL License version4* if that is ever needed to be published.

**Comment by bartfeenstra** [comment]
@patlx @rainerth Do you consent to having your contributions to Betty (French and German translations respectively) re-released under the *GPL License version 3 or newer*?

**Comment by bartfeenstra** [comment]
@patlx @rainerth ping :)

**Comment by patlx** [comment]
Sure, you can.

Le sam. 27 juil. 2024, 14:53, Bart Feenstra ***@***.***> a
écrit :

**Comment by rainerth** [comment]
That's a great idea. I agree to change the license to GPL3 or later. Thank you for your work!
Rainer

**Comment by bartfeenstra** [comment]
@patlx @rainerth Thank you both!
