### ISSUE TITLE
Support relative media paths for Gramps family trees 

### ISSUE THREAD

**Issue by bartfeenstra** [bartfeenstra/betty#2193]
@Illia-M I believe this is the problem you ran into, where your family tree uses relative paths to reference media files on your disk.

https://gramps.discourse.group/t/default-media-path-storage/79/3 indicates the necessary information to handle this automatically is included in the Gramps exports. If that is (still) true, we should be able to fix this with a couple of lines added to `GrampsLoader`.

**Comment by Illia-M** [comment]
Yes, all my Gramps DBs use relative path to files - that like best practice, as I understand

**Comment by bartfeenstra** [comment]
It is indeed. You did nothing wrong here :)

**Comment by bartfeenstra** [comment]
@Illia-M Also be sure to use https://betty.readthedocs.io/0.4.x when consulting the documentation. Because 0.4.x is not yet stable, the documentation site still defaults to 0.3.x.

**Comment by Illia-M** [comment]
I know but still I'm not understand what to do.
Issue still in my case, you can get Grmaps example tree that I use in repo(https://github.com/Illia-M/test-betty-tree/blob/main/tree.gpkg).
Pipeline:
https://github.com/Illia-M/test-betty-tree/actions/runs/11699095682/job/33033826124#step:6:13 

I'm trying create example solution for researches from Ukraine to be able "copy paste" repo and get beautiful family tree site, but I can't get what I'm doing wrong
