### ISSUE TITLE
Featured person image not showing

### ISSUE THREAD

**Issue by uwagura** [bartfeenstra/betty#2196]
Hello again! I recently tried changing the colors used by cotton candy and adding a featured person to my webpages home screen, but the colors of my screen did not update and the image associated with this person is not displaying. Betty is still using the default theming, and only the alt-text associated with the image is displayed: 
![Betty_no_images_blocked](https://github.com/user-attachments/assets/4a092dc0-1f98-48fe-bac0-a1283d80f943)

( the link that says Cucuandguka is supposed to be an image) I don't *think* the issue with my browser (Firefox 132) as I get the same issue with the latest version of Chrome. I'm running the KDE Spin of Fedora 40, version Node.js version `v22.11.0` and npm version `10.9.0`. My yaml file has the following config: 
```
clean_urls: false
debug: true
entity_types:
  Event:
    generate_html_list: false
  File:
    generate_html_list: false
  Note:
    generate_html_list: false
  Person:
    generate_html_list: true
  Place:
    generate_html_list: true
extensions:
  betty.extension.CottonCandy:
    configuration:
      link_active_color: '#00a700'
      link_inactive_color: '#006500'
      primary_active_color: '#bb0000'
      primary_inactive_color: '#ff393c'
      featured_entities:
      - entity_id: I0006
        entity_type: Person
    enabled: true
  betty.extension.Gramps:
    configuration:
      family_trees:
      - file: <path_to_file>/webtree.gramps
    enabled: true
  betty.extension.Maps:
    enabled: false
  betty.extension.Trees:
    enabled: true
lifetime_threshold: 125
locales:
  en-US: {}
name: ancestry
root_path: ''
```
And the my betty config is unchanged from my last issue: 
```
Betty                   0.3.14
Operating system        Linux-6.8.5-301.fc40.x86_64-x86_64-with-glibc2.39
Python                  3.12.7 (main, Oct  1 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
Python packages         aiofiles                             23.2.1
                        aiohappyeyeballs                     2.4.3
                        aiohttp                              3.10.10
                        aiosignal                            1.3.1
                        alabaster                            0.7.16
                        attrs                                24.2.0
                        babel                                2.16.0
                        beautifulsoup4                       4.12.3
                        betty                                0.3.14
                        certifi                              2024.8.30
                        charset-normalizer                   3.4.0
                        click                                8.1.7
                        docker                               7.1.0
                        docutils                             0.21.2
                        frozenlist                           1.5.0
                        furo                                 2024.5.6
                        geographiclib                        2.0
                        geopy                                2.4.1
                        html5lib                             1.1
                        idna                                 3.10
                        imagesize                            1.4.1
                        Jinja2                               3.1.4
                        jsonschema                           4.23.0
                        jsonschema-specifications            2024.10.1
                        langcodes                            3.4.1
                        language_data                        1.2.0
                        marisa-trie                          1.2.1
                        MarkupSafe                           2.1.5
                        multidict                            6.1.0
                        packaging                            24.1
                        pdf2image                            1.17.0
                        pillow                               10.4.0
                        pip                                  24.3.1
                        polib                                1.2.0
                        propcache                            0.2.0
                        Pygments                             2.18.0
                        PyQt6                                6.7.1
                        PyQt6-Qt6                            6.7.3
                        PyQt6_sip                            13.8.0
                        PyYAML                               6.0.2
                        referencing                          0.35.1
                        requests                             2.32.3
                        rpds-py                              0.20.0
                        setuptools                           75.2.0
                        six                                  1.16.0
                        snowballstemmer                      2.2.0
                        soupsieve                            2.6
                        Sphinx                               7.4.7
                        sphinx-autodoc-typehints             2.3.0
                        sphinx-basic-ng                      1.0.0b2
                        sphinx_design                        0.6.1
                        sphinxcontrib-applehelp              2.0.0
                        sphinxcontrib-devhelp                2.0.0
                        sphinxcontrib-htmlhelp               2.1.0
                        sphinxcontrib-jsmath                 1.0.1
                        sphinxcontrib-qthelp                 2.0.0
                        sphinxcontrib-serializinghtml        2.0.0
                        typing_extensions                    4.12.2
                        urllib3                              2.2.3
                        webencodings                         0.5.1
                        yarl                                 1.17.0

```
Let me know if you can help out with this issue, and thanks again!

**Comment by bartfeenstra** [comment]
@uwagura Thanks for the report! Would you be able to:
- Richt-click the image in your browser, and open it in a new tab. Check the URL, and paste it here?
- See if the same problems occur with Betty 0.4.0b2 (this is slightly more work as your configuration file will need a few changes, but that will have to happen sooner rather than later, as 0.4.0 will replace 0.3.x over the coming weeks)

**Comment by uwagura** [comment]
>     * Richt-click the image in your browser, and open it in a new tab. Check the URL, and paste it here?
It just opens up the page for my featured person : `http://localhost:8000/person/I0006/index.html`

>     * See if the same problems occur with Betty 0.4.0b2 (this is slightly more work as your configuration file will need a few changes, but that will have to happen sooner rather than later, as 0.4.0 will replace 0.3.x over the coming weeks)
I will try this tomorrow and update this comment!

**Comment by bartfeenstra** [comment]
> It just opens up the page for my featured person : `http://localhost:8000/person/I0006/index.html`

That looks like you may have opened the link itself, rather than the image shown inside of it. When right-clicking (or left-clicking if your mouse settings are left-handed), in the context menu, choose to open the image, and not the link. The reason is that the browser has no trouble showing the link, but somehow can't show you the image. Either the file does not exist at the location specified in the HTML page, or the file it refers to is not an image that a browser can display. Checking the URL helps us find out more about this.

**Comment by uwagura** [comment]
@bartfeenstra , ah,my mistake. Yeah it doesn't seem to be finding the image when I try to open it. It tries to go to the link `http://localhost:8000/file/O0012-500x500.png`, which gives me a 404 error
![image](https://github.com/user-attachments/assets/ff38e26b-b437-4366-b5ca-72dd6e29889d)

**Comment by uwagura** [comment]
Ah wait: so the photo I have attached to my featured person is also the photo I am using for their spouse within my tree. It looks like Betty cannot display because it is shared between two people. When I change my feature person to someone who has their own media file, betty displays it correctly. 

Interestingly though, betty still isn't using the custom theming I have in the above config file.

**Comment by bartfeenstra** [comment]
Let's continue the color configuration issue in https://github.com/bartfeenstra/betty/issues/2199 (one topic per issue, please).

With regards to the files: sharing files between other entities is fully supported and working. Thank you also for providing that screen shot, as it confirms that Betty managed to find the original file and resize it.

Just double-checking, if you run `betty clear-caches` and re-generate your site, does the problem persist?

**Comment by uwagura** [comment]
> Let's continue the color configuration issue in #2199 (one topic per issue, please).

Thanks for pointing me to the new issue!

> With regards to the files: sharing files between other entities is fully supported and working

Are you able to display images that are shared between people in your tree ( if you have any?). By my previous comment, I meant that I'm only getting this issue for files that are shared between people in my tree. If I change my featured person to someone who has their own media file, it displays correctly on the home screen, and I can open their image in a new tab.

> Just double-checking, if you run `betty clear-caches` and re-generate your site, does the problem persist?

Yes, I still have the problem even after clearing caches.

**Comment by bartfeenstra** [comment]
I literally just released 0.4.0b3, which includes the fix for the color configuration :)

> Are you able to display images that are shared between people in your tree ( if you have any?). By my previous comment, I meant that I'm only getting this issue for files that are shared between people in my tree. If I change my featured person to someone who has their own media file, it displays correctly on the home screen, and I can open their image in a new tab.

Yes, https://ancestry.bartfeenstra.com/en/file/O0213/ is an example of a file entity associated with multiple people. This site now runs Betty 0.4.x, but it worked the same with Betty 0.3.x until the upgrade recently.

Now that I'm thinking about this again, I wonder if this is due to a privacy issue, where the file may be considered private and therefore not published, but that one of the templates does not properly check if the file is public, and renders HTML for it regardless. Depending on your configuration, there are one or two ways to check this:
1) Confirm that file `O0012` is not marked private in Gramps (the padlock icon when editing the file in its own window).
2) **If you use the Privatizer extension**, try disabling it and see if the problem persists (it's not the Privatizer's fault, but it'll help us narrow down the cause)

**Comment by uwagura** [comment]
> I literally just released 0.4.0b3, which includes the fix for the color configuration :)

Great, thanks!

>     1. Confirm that file `O0012` is not marked private in Gramps (the padlock icon when editing the file in its own window).

It's not marked private, and I don't use the privitizer extension. Interestingly though, I tried changing my featured person to the other person who uses this image ( i.e person `I0006`'s spouse) , and it displayed correctly. It looks like even though the two people are using the same media file, it's labelled as a different object in gramps for each person, and the other object can be displayed correctly for some reason.

**Comment by bartfeenstra** [comment]
Is the file/media entity `O0012` associated with both people in Gramps? Or you you have two different file/media entities in Gramps, that both point to the same file path on disk?

**Comment by uwagura** [comment]
I have two different media entries in gramps that point to the same file path on disk

**Comment by bartfeenstra** [comment]
Thanks for confirming! Not a situation I had ever envisioned, but we should support that.

Now that we understand the specifics, I can work on a test case that lets us pinpoint the exact location of the bug.

**Comment by bartfeenstra** [comment]
I tried reproducing this (see [diff](https://github.com/bartfeenstra/betty/compare/reproduce-2196)), but so far it works on the latest 0.4.x. What it does, is create two file entities, each pointing to the same file on disk, and it assigns each file entity to a different person. I think that's what happens in your family tree.

Install this locally with `pip install git+https://github.com/bartfeenstra/betty.git@reproduce-2196`

**Comment by uwagura** [comment]
> Install this locally with `pip install git+https://github.com/bartfeenstra/betty.git@reproduce-2196`

I installed this version of betty and generated a new yaml files using the `betty new` command. I then tried to add a featured entity to the yaml using the template on the [0.4.x](https://betty.readthedocs.io/0.4.x/usage/extension/cotton_candy/) version of the docs, but I keep getting this error: 
```
Error: "Person" is not a valid machine name: only lowercase letters, digits, and hyphens (-) are allowed.
```
Let me know if there is something else I need to change for the 0.4.x version of betty 

Out of curiosity, how did you add the media file associated with multiple people to your tree? I think I ended up with separate objects for the same media file because I added the same photo to the gallery section of two different individuals, causing it to show up as separate entries within my family tree. I'm not sure if this is how gramps recommends associating individuals to family trees, but at the same time I don't see any official guidelines in the documentation. 

In any case, I don't think adding support for this feature is _too_ urgent, as I can get by switching the feature person in my tree, and I am not sure how common my situation is. In any case, thanks again for your help!

**Comment by bartfeenstra** [comment]
Entity type IDs have changed from fully qualified class names to lowercase hyphenated strings in Betty 0.4 (the documentation is yet to be properly updated, it's on my list!). For example, `Person` has become `person`, and `PersonName` has become `person-name`. See https://github.com/bartfeenstra/ancestry/blob/betty-0.4/betty.yaml for an accurate example of a Betty 0.4.x configuration file.

> Out of curiosity, how did you add the media file associated with multiple people to your tree? I think I ended up with separate objects for the same media file because I added the same photo to the gallery section of two different individuals, causing it to show up as separate entries within my family tree. I'm not sure if this is how gramps recommends associating individuals to family trees, but at the same time I don't see any official guidelines in the documentation.

I'm not sure if you can read Python (see the link in my previous comment if you do), but what I did was create two separate file entities pointing to the same file on disk.  Then I assigned each file entity to a different person, and ensure both people are featured entities on the front page. `pip install git+https://github.com/bartfeenstra/betty.git@reproduce-2196` and then `betty demo -vv` will show you the result in your browser.

For my information, are you using the latest Betty 0.4 release to test this now?

**Comment by uwagura** [comment]
> I'm not sure if you can read Python (see the link in my previous comment if you do), but what I did was create two separate file entities pointing to the same file on disk. Then I assigned each file entity to a different person, and ensure both people are featured entities on the front page. `pip install git+https://github.com/bartfeenstra/betty.git@reproduce-2196` and then `betty demo -vv` will show you the result in your browser.
>

I installed that version of betty and ran the demo site. It looks like Liberta and Johan now have each not have a copy of the betty logo in their media sections, but their other images are not showing up. Is this what you intended?

![Betty_betty](https://github.com/user-attachments/assets/77bb2d63-8776-4aca-8741-d1bd25b62555)
![Betty_Johan](https://github.com/user-attachments/assets/60faea4c-4267-4c0c-b09b-4ac538086922)

> Entity type IDs have changed from fully qualified class names to lowercase hyphenated strings in Betty 0.4

Thanks for clarifying. I made the changes, and when I set person `I0006` as my featured person in betty 0.4, their image displays correct. So it looks like this problem isn't occuring for me using version 0.4

When I asked my original question about how you shared a single media file between two people, I was referring to when you made the tree originally using gramps ( assuming you used gramps).  Using the procedure I described above causes gramps to create to separate media objects pointing to the same file. In hindsight, I'm not sure if this is how the developers intended users to associate media objects with multiple people, and I think this might have caused this bug.

**Comment by bartfeenstra** [comment]
> I installed that version of betty and ran the demo site. It looks like Liberta and Johan now have each not have a copy of the betty logo in their media sections, but their other images are not showing up. Is this what you intended?

What I intended was to show, using those logos, that having two file entities referencing the same files on disk works. I don't know what you mean with "other images". This is the built-in demo site, there simply are no other images in there besides the ones in your screenshot.

> When I asked my original question about how you shared a single media file between two people, I was referring to when you made the tree originally using gramps ( assuming you used gramps). Using the procedure I described above causes gramps to create to separate media objects pointing to the same file. In hindsight, I'm not sure if this is how the developers intended users to associate media objects with multiple people, and I think this might have caused this bug.

There shouldn't be any technical reason why you can't do what you did. However, you would have two file entities in your family tree describing the exact same file on disk. That would mean you have two file entities that are exactly similar, except for their entity IDs. While this is perfectly possible, most people generally want to **deduplicate** their data.

I'm glad that things work now :)

**Comment by bartfeenstra** [comment]
@uwagura Also be sure to use https://betty.readthedocs.io/0.4.x when consulting the documentation. Because 0.4.x is not yet stable, the documentation site still defaults to 0.3.x.
