### ISSUE TITLE
Person unhashable type

### ISSUE THREAD

**Issue by unixmiddleware** [bartfeenstra/betty#627]
When trying to generate 
  File "/home/mark/workspace/betty/betty/assets/templates/page/source.html.j2", line 13, in block "page_content"
    {% set facts = sources | map(attribute='citations') | flatten | map(attribute='facts') | flatten | select('resource') | list | set | list %}
TypeError: unhashable type: 'Person'

Using strace this occurs after import of macro/person.html.j2

16865 openat(AT_FDCWD, "/home/mark/workspace/betty/betty/assets/templates/base.html.j2", O_RDONLY|O_CLOEXEC) = 7
16865 fstat(7, {st_mode=S_IFREG|0644, st_size=9385, ...}) = 0
16865 ioctl(7, TCGETS, 0x7ffc79af6e30)  = -1 ENOTTY (Inappropriate ioctl for device) 
16865 lseek(7, 0, SEEK_CUR)             = 0
16865 read(7, "{%- import 'macro/person.html.j2"..., 4096) = 4096
16865 read(7, "erson_name %}\n                  "..., 8192) = 5289
16865 read(7, "", 8192)                 = 0
16865 close(7)                          = 0
16865 write(2, "\33[91munhashable type: 'Person'\nT"..., 2852) = 2852

**Comment by bartfeenstra** [comment]
@unixmiddleware Can you review https://github.com/bartfeenstra/betty/pull/628 ?
