### ISSUE TITLE
Outdated `assets` configuration documentation

### ISSUE THREAD

**Issue by bartfeenstra** [bartfeenstra/betty#774]
The README still mentions `assets_directory_path`, which is what the `assets` configuration key was called in 0.2.x.

## Definition of Done
- Ensure all mentions of the `assets_directory_path` configuration file key are replaced with `assets`. Note that on the `Configuration` class this configuration setting is still called `assets_directory_path` by design, as the configuration file uses shorthand naming for improved User Experience for less-technical users.

**Comment by erikvegax** [comment]
hey @bartfeenstra! mind if i grab this one? i've been wanting to contribute to open source.

**Comment by erikvegax** [comment]
just for clarification, i should replace the mention of `assets_directory_path` to `assets` in the README?

**Comment by bartfeenstra** [comment]
@erikvega Go ahead! :blush: Yes. Check if there are any other mentions of that **configuration file key** in 0.3.x elsewhere, but I don't think so. There's the `Configuration.assets_directory_path` attribute but that should stay the way it is.

**Comment by erikvegax** [comment]
@bartfeenstra Yeah, not seeing any other mention of it except for in the block you specified! Hopefully, Ctrl+F didn't lie to me.

**Comment by bartfeenstra** [comment]
@erikvega Hiya! Are you still interesting in working on this? :)

**Comment by bartfeenstra** [comment]
@erikvega Ping :)
