### ISSUE TITLE
Limit the Death date estimation to people considered dead

### ISSUE THREAD

**Issue by leyan** [bartfeenstra/betty#896]
As soon as a person has a Marriage date, a Death date will be generated, with the form "sometime after MarriageDate". While technically true, that is not something people really want to read about themselves!

It would be better to limit this to people we know are dead (Birth date or Marriage date farther than the "lifetime_threshold").

**Comment by bartfeenstra** [comment]
Thanks for reporting this. I originally added this functionality to be helpful but like you, found that it's pretty odd to see about people that we know are still alive. Let's think about how we want to implement this. The code to create new derived events is meant to be pretty generic, so ideally we'd come up with a generic solution that works for deaths and perhaps other types of events as well.
