### ISSUE TITLE
Make the Cotton Candy Betty logo customizable 

### ISSUE THREAD

**Issue by bartfeenstra** [bartfeenstra/betty#922]
## Definition of Done
- Make the Betty logo an SVG and apply the primary color as the background
- Allow users to choose a different logo altogether, and apply that to semantic/structured metadata (OG), the web manifest, and the theme header.

## Blocked by 
- https://github.com/bartfeenstra/betty/issues/1404

**Comment by emyoulation** [comment]
How about changing from the Cotton Candy Betty to a Betty Boop logo? There are plenty of variants in the public domain. And some of the images for WWII have her with various occupation hats.
