### ISSUE TITLE
Request a good screen capture to jazz up the Betty listing on the Gramps wiki and discourse 

### ISSUE THREAD

**Issue by emyoulation** [bartfeenstra/betty#923]
Could you make an instance using the [example.gramps](https://www.gramps-project.org/wiki/index.php/Example.gramps) tree with Lewis Garner von Zielinksi person?  It has become the standard comparative illustration.

![image](https://user-images.githubusercontent.com/69127217/202754311-6ef0e794-ff83-4f13-9321-7496c313c350.png)

I would like to add an image to the [Web Solutions for Gramps](https://gramps-project.org/wiki/index.php?title=Web_Solutions_for_Gramps#External_tools_that_leverage_Gramps_XML) section and the [Discourse thread](https://gramps.discourse.group/t/web-connected-versus-stand-alone-isolated-genealogy-application/889/7)

**Comment by bartfeenstra** [comment]
That's a good idea! If you'd like the example family tree to be reflected, this would mean screen shots of the generated site. Additionally, there's the CLI and desktop application that do not really show anything related to the specific family tree, except how to configure the Gramps extension to load the tree from a specific Gramps file.

I'm currently in the process of refreshing the site's look and feel in anticipation of Betty 0.3.0. I'll make some screen shots when the updated design has landed :)

**Comment by bartfeenstra** [comment]
We're nearing the Betty 0.3.0 release and won't be seeing any major differences in how the sites will look. If you [install](https://betty.readthedocs.io/latest/installation.html) Betty and [configure Gramps](https://betty.readthedocs.io/latest/usage/extension/gramps.html) , you can render a site in minutes and take the necessary screenshots.

**Comment by bartfeenstra** [comment]
You may also link to https://ancestry.bartfeenstra.com/. I'm looking to host a live demo site somewhere soon (same site as the built-in demo), and once Gramps is pip-installable I'll do the same for the Gramps example family tree.
