### ISSUE TITLE
extra keys not allowed @ data['debug']

### ISSUE THREAD

**Issue by khlsvr** [bartfeenstra/betty#942]
I created a venv, I have python 3.10, then pip installed betty there. I have a gramps.gpkg file I have exported in the betty's dir. First I had the problem in https://github.com/bartfeenstra/betty/issues/937 I fixed it with the solution provided there. Then I'm getting this:

$  betty generate
Loading the site from /home/user/files/venv/betty/betty.yaml.
extra keys not allowed @ data['debug']
- in /home/user/files/venv/betty/betty.yaml

Running `betty gui` gives same output.

The betty.yaml file looks like this. I changed the text 'myserver' in place of the correct one:
```
base_url: https://myserver.eu.org
debug: true
root_path: /betty
clean_urls: true
title: ancestry
author: test
lifetime_threshold: 125
locales:
  - locale: en-US
    alias: en
entity_types:
  Person:
    generate_html_list: true
  File:
    generate_html_list: false
extensions:
  betty.anonymizer.Anonymizer: {}
  betty.cleaner.Cleaner: {}
  betty.cotton_candy.CottonCandy:
    configuration:
      primary_inactive_color: '#ffc0cb'
      primary_active_color: '#ff69b4'
      link_inactive_color: '#149988'
      link_active_color: '#2a615a'
      featured_entities:
        - entity_type: Place
          entity_id: P0099
  betty.deriver.Deriver: {}
  betty.gramps.Gramps:
    configuration:
      family_trees:
        - file: ./gramps.gpkg
  betty.http_api_doc.HttpApiDoc: {}
  betty.maps.Maps: {}
  betty.privatizer.Privatizer: {}
  betty.trees.Trees: {}
  betty.wikipedia.Wikipedia: {}
```

Using -c option to load betty.yaml says I don't have this file:

```
$  pwd
/home/user/files/venv/betty
$  ls
betty.yaml  betty.yaml~  bin  gramps.gpkg  include  lib  lib64  LICENSE.txt  pyvenv.cfg  README.md  VERSION
(betty) [user@user betty]$  betty -c betty.yaml generate
Loading the site from betty.yaml.
Configuration file "betty.yaml" does not exist.
(betty) [user@user betty]$  betty generate
Loading the site from /home/user/files/venv/betty/betty.yaml.
extra keys not allowed @ data['debug']
- in /home/user/files/venv/betty/betty.yaml
```

**Comment by bartfeenstra** [comment]
Could it be that you are running [Betty 0.2](https://github.com/bartfeenstra/betty/tree/0.2.x)?

Your configuration sample is for Betty 0.3, which is still in development and unavailable through pip/PyPI, but is shown on the GitHub project's front page.

**Comment by bartfeenstra** [comment]
Please see https://github.com/bartfeenstra/betty/pull/969 for a potential solution to https://github.com/bartfeenstra/betty/issues/937 :)

**Comment by bartfeenstra** [comment]
Feel free to reopen this issue if the problem persists :)

**Comment by ptalmeida** [comment]
just did a fresh install with pip on macos, problem persists.
e: I understand it now from this issue, but the documentation gives no indication about this difference of configs

**Comment by bartfeenstra** [comment]
We've made big steps to communicate this more clearly in the 0.3.x branch. Once [Betty 0.3.0 is released](https://github.com/bartfeenstra/betty/issues/1249), the current version and accurate documentation should automatically show up much more clearly in the Github README, the documentation site, as well as PyPI.
