### ISSUE TITLE
Fix broken README

### ISSUE THREAD

**Issue by Sternbach-Software** [bartfeenstra/betty#994]
The YAML in the readme uses the syntax:
```
locales:
  - locale: en-US
```
When really it should be:
```
locales:
  en-US: {}
```
There should also be mention of how to properly resolve the errors that "betty.npm._Npm is required".

**Comment by bartfeenstra** [comment]
Thank you for reporting the problems with the README. These will be fixed by the two linked PRs shortly, with the second documenting that Node.js is needed when installing through pip. In a future, we'll revise the Npm requirement so it'll be more helpful without having to read the README.
